apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-restx-api-hpa
  namespace: neo4j
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-restx-api-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
      name: memory
      target:
        type: Utilization
        averageUtilization: 75