apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: neo4j-tls
  namespace: neo4j
spec:
  secretName: neo4j-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - neo4j.notello.ai
  subject:
    organizations:
    - Notello