apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neo4j-ingress
  namespace: neo4j
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - neo4j.notello.ai
    secretName: neo4j-tls
  rules:
  - host: neo4j.notello.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-neo4j
            port: 
              number: 7474