---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-deployment
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: neo4j-pool
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "neo4j"
        effect: "NoSchedule"
      initContainers:
      - name: init-certificates
        image: busybox
        command: ['sh', '-c', 'cp /certificates/* /neo4j-certificates/ && chmod -R 777 /neo4j-certificates/']
        volumeMounts:
        - name: certificates
          mountPath: /certificates
        - name: neo4j-certificates
          mountPath: /neo4j-certificates
      containers:
      - name: neo4j
        image: neo4j:4.4-community
        ports:
        - containerPort: 7474
        - containerPort: 7473
        - containerPort: 7687
        env:
        - name: NEO4J_AUTH
          value: neo4j/!neo4j!password!Aa280102423!
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        - name: NEO4JLABS_PLUGINS
          value: '["apoc"]'
        - name: NEO4J_dbms_default__listen__address
          value: "0.0.0.0"
        - name: NEO4J_dbms_connector_bolt_advertised__address
          value: "neo4j.notello.ai:7687"
        - name: NEO4J_dbms_connector_bolt_enabled
          value: "true"
        - name: NEO4J_dbms_connector_bolt_tls__level
          value: "REQUIRED"
        - name: NEO4J_dbms_connector_https_advertised__address
          value: "neo4j.notello.ai:7473"
        - name: NEO4J_dbms_connector_http_advertised__address
          value: "neo4j.notello.ai:7474"
        - name: NEO4J_dbms_connector_https_enabled
          value: "true"
        - name: NEO4J_dbms_connector_http_enabled
          value: "true"
        - name: NEO4J_dbms_connector_http_listen__address
          value: "0.0.0.0:7474"
        - name: NEO4J_dbms_connector_https_listen__address
          value: "0.0.0.0:7473"
        - name: NEO4J_dbms_connector_bolt_listen__address
          value: "0.0.0.0:7687"
        - name: NEO4J_dbms_ssl_policy_bolt_enabled
          value: "true"
        - name: NEO4J_dbms_ssl_policy_bolt_base__directory
          value: "/var/lib/neo4j/certificates"
        - name: NEO4J_dbms_ssl_policy_bolt_private__key
          value: "tls.key"
        - name: NEO4J_dbms_ssl_policy_bolt_public__certificate
          value: "tls.crt"
        - name: NEO4J_dbms_ssl_policy_bolt_client__auth
          value: "NONE"
        - name: NEO4J_dbms_ssl_policy_https_enabled
          value: "true"
        - name: NEO4J_dbms_ssl_policy_https_base__directory
          value: "/var/lib/neo4j/certificates"
        - name: NEO4J_dbms_ssl_policy_https_private__key
          value: "tls.key"
        - name: NEO4J_dbms_ssl_policy_https_public__certificate
          value: "tls.crt"
        - name: NEO4J_dbms_ssl_policy_https_client__auth
          value: "NONE"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: neo4j-certificates
          mountPath: /var/lib/neo4j/certificates
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: certificates
        secret:
          secretName: neo4j-tls
      - name: neo4j-certificates
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j
  ports:
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: https
      protocol: TCP
      port: 7473
      targetPort: 7473
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-bolt-service
spec:
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
  type: LoadBalancer