apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: neo4j
data:
  NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
  NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,gds.*'
  NEO4J_dbms_security_procedures_whitelist: 'apoc.*,gds.*'
  NEO4J_dbms_jvm_additional: "-Dneo4j.ext.udc.source=docker"