apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neo4j-hpa
  namespace: neo4j
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: my-neo4j-release
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100