---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-taint-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-taint-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-taint-rolebinding
subjects:
- kind: ServiceAccount
  name: node-taint-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-taint-role
  apiGroup: rbac.authorization.k8s.io