---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-restx-api-deployment
  namespace: neo4j
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-restx-api
  template:
    metadata:
      labels:
        app: flask-restx-api
    spec:
      nodeSelector:
        dedicated: api
      containers:
      - name: flask-restx-api
        image: registry.digitalocean.com/notello/api-dev:v3.11
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "6500m"
            memory: "11Gi"
          limits:
            cpu: "6500m"
            memory: "11Gi"
        env:
        - name: FLASK_ENV
          value: "production"
        - name: ENV_TYPE
          value: "prod"
        - name: YOUTUBE_API_KEY
          value: "AIzaSyBHW4s93q5pmBT35zwll_oeHWGNJsCgX4M"
        - name: NEO4J_URI
          value: "neo4j://my-neo4j-release:7687"
        - name: NEO4J_USERNAME
          valueFrom:
            secretKeyRef:
              name: neo4j-secrets
              key: username
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-secrets
              key: password
        - name: NEO4J_DATABASE
          value: "neo4j"
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis
              key: host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis
              key: port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: url
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: service-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: openai
        - name: FAL_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: fal
        - name: GROQ_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: groq
        - name: RUNPOD_WHISPER_ENDPOINT_ID
          value: "amyg6f231rop31"
        - name: RUNPOD_GDS_ENDPOINT_ID
          value: "7ln9bgb6daqlr6"
        - name: RUNPOD_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: runpod
      imagePullSecrets:
      - name: registry-notello
---
apiVersion: v1
kind: Service
metadata:
  name: flask-restx-api-service
  namespace: neo4j
spec:
  selector:
    app: flask-restx-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flask-restx-api-ingress
  namespace: neo4j
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.notello.dev`)
      kind: Rule
      services:
        - name: flask-restx-api-service
          port: 80