apiVersion: batch/v1
kind: CronJob
metadata:
  name: neo4j-backup
  namespace: neo4j
spec:
  schedule: "0 1 * * *"  # Run daily at 1:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: neo4j-backup
            image: registry.digitalocean.com/notello/neo4j-backup:v1
            volumeMounts:
            - name: backup-storage
              mountPath: /backups
            envFrom:
            - secretRef:
                name: neo4j-secrets
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: neo4j-backup-pvc